# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_detaildialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DetailDialog(object):
    def setupUi(self, DetailDialog):
        DetailDialog.setObjectName("DetailDialog")
        DetailDialog.resize(412, 396)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("dome.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DetailDialog.setWindowIcon(icon)
        DetailDialog.resize(412, 244)

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DetailDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblName = QtWidgets.QLabel(DetailDialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lblName.setFont(font)
        self.lblName.setTextFormat(QtCore.Qt.PlainText)
        self.lblName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblName.setObjectName("lblName")
        self.horizontalLayout_2.addWidget(self.lblName)
        self.lblPhoto = QtWidgets.QLabel(DetailDialog)
        self.lblPhoto.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPhoto.setObjectName("lblPhoto")
        self.horizontalLayout_2.addWidget(self.lblPhoto)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setHorizontalSpacing(5)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(DetailDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.textState = QtWidgets.QLineEdit(DetailDialog)
        self.textState.setObjectName("textState")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textState)
        self.label_3 = QtWidgets.QLabel(DetailDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.textChamber = QtWidgets.QLineEdit(DetailDialog)
        self.textChamber.setObjectName("textChamber")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textChamber)
        self.label_4 = QtWidgets.QLabel(DetailDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.textParty = QtWidgets.QLineEdit(DetailDialog)
        self.textParty.setObjectName("textParty")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textParty)
        self.label_5 = QtWidgets.QLabel(DetailDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.textBirthday = QtWidgets.QLineEdit(DetailDialog)
        self.textBirthday.setObjectName("textBirthday")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textBirthday)
        self.label_6 = QtWidgets.QLabel(DetailDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.textPhone = QtWidgets.QLineEdit(DetailDialog)
        self.textPhone.setObjectName("textPhone")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.textPhone)
        self.label_7 = QtWidgets.QLabel(DetailDialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.textAddress = QtWidgets.QLineEdit(DetailDialog)
        self.textAddress.setObjectName("textAddress")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.textAddress)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblContact = QtWidgets.QLabel(DetailDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblContact.sizePolicy().hasHeightForWidth())
        self.lblContact.setSizePolicy(sizePolicy)
        self.lblContact.setAlignment(QtCore.Qt.AlignCenter)
        self.lblContact.setObjectName("lblContact")
        self.horizontalLayout.addWidget(self.lblContact)
        self.lblWeb = QtWidgets.QLabel(DetailDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblWeb.sizePolicy().hasHeightForWidth())
        self.lblWeb.setSizePolicy(sizePolicy)
        self.lblWeb.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWeb.setObjectName("lblWeb")
        self.horizontalLayout.addWidget(self.lblWeb)
        self.lblVoteSmart = QtWidgets.QLabel(DetailDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblVoteSmart.sizePolicy().hasHeightForWidth())
        self.lblVoteSmart.setSizePolicy(sizePolicy)
        self.lblVoteSmart.setAlignment(QtCore.Qt.AlignCenter)
        self.lblVoteSmart.setObjectName("lblVoteSmart")
        self.horizontalLayout.addWidget(self.lblVoteSmart)
        self.lblGovTrack = QtWidgets.QLabel(DetailDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGovTrack.sizePolicy().hasHeightForWidth())
        self.lblGovTrack.setSizePolicy(sizePolicy)
        self.lblGovTrack.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGovTrack.setObjectName("lblGovTrack")
        self.horizontalLayout.addWidget(self.lblGovTrack)
        self.lblCrp = QtWidgets.QLabel(DetailDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCrp.sizePolicy().hasHeightForWidth())
        self.lblCrp.setSizePolicy(sizePolicy)
        self.lblCrp.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCrp.setObjectName("lblCrp")
        self.horizontalLayout.addWidget(self.lblCrp)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(DetailDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(DetailDialog)
        QtCore.QMetaObject.connectSlotsByName(DetailDialog)

    def retranslateUi(self, DetailDialog):
        _translate = QtCore.QCoreApplication.translate
        DetailDialog.setWindowTitle(_translate("DetailDialog", "Open Congress"))
        self.lblName.setText(_translate("DetailDialog", "Name"))
        self.lblPhoto.setText(_translate("DetailDialog", "Photo Here"))
        self.label_2.setText(_translate("DetailDialog", "State"))
        self.label_3.setText(_translate("DetailDialog", "Chamber"))
        self.label_4.setText(_translate("DetailDialog", "Party"))
        self.label_5.setText(_translate("DetailDialog", "Birthday"))
        self.label_6.setText(_translate("DetailDialog", "Phone"))
        self.label_7.setText(_translate("DetailDialog", "Address"))
        self.lblContact.setText(_translate("DetailDialog", "Link"))
        self.lblWeb.setText(_translate("DetailDialog", "Link"))
        self.lblVoteSmart.setText(_translate("DetailDialog", "Link"))
        self.lblGovTrack.setText(_translate("DetailDialog", "Link"))
        self.lblCrp.setText(_translate("DetailDialog", "Link"))

